# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors = ["andornaut"]
description = """
FileCTRL is a light, opinionated, responsive, theme-able, and simple Text User Interface (TUI) file manager for Linux and macOS
"""
edition = "2021"
license = "MIT"
name = "filectrl"
readme = "README.md"
repository = "https://github.com/andornaut/filectrl"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
argh = "0.1.12"
chrono = {version = "0.4.26", default-features = false, features = ["clock", "time"]}
color-to-tui = "0.3.0"
crossterm = "0.26.1"
etcetera = "0.8.0"
open = "5.0.0"
ratatui = {version = "0.22.0", features = ["all-widgets"]}
regex = "1.9.3"
serde = "1.0.183"
toml = "0.7.6"
tui-input = "0.7.1"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"
unix_mode = "0.1.3"

[dev-dependencies]
test-case = "3.1.0"

[dev-dependencies.cargo-husky]
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-test", "run-cargo-check"] 
version = "1" 

[profile.release]
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
lto = true # Enable Link Time Optimization
opt-level = 'z' # Optimize for size.
panic = 'abort' # Abort on panic
strip = true # Symbols from Binary
