# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors = ["andornaut"]
description = """
FileCTRL is a light, opinionated, responsive, theme-able, and simple Text User Interface (TUI) file manager for Linux and macOS
"""
edition = "2021"
license = "MIT"
name = "filectrl"
readme = "README.md"
repository = "https://github.com/andornaut/filectrl"
version = "0.1.0"

[dependencies]
anyhow = "~1.0"
argh = "0.1"
chrono = {version = "0.4.40", default-features = false, features = ["clock"]}
cli-clipboard = "0.4"
env_logger = {version = "0.10.0", default-features = false}
etcetera = "0.8"
log = {version = "0.4.20", default-features = false, features = ["serde"]}
nix = {version = "0", default-features = false, features = ["user"]}
notify = "8.0.0"
open = "~5.0"
rat-widget = "1.0.5"
ratatui = {version = "0.29.0", features = ["all-widgets", "serde"]}
serde = {version = "1.0.218", features = ["derive"]}
smart-default = "0.7"
textwrap = "0.16"
toml = "0.7"
unicode-width = "0.1"
unix_mode = "0.1"

[dev-dependencies]
cargo-husky = {version = "1", default-features = false, features = ["precommit-hook", "run-cargo-test", "run-cargo-check"]}
test-case = "~3.1"

[profile.release]
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
lto = true # Enable Link Time Optimization
opt-level = 3 # Optimize for performance
panic = 'abort' # Abort on panic
strip = true # Symbols from Binary
