# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors = ["andornaut"]
description = """
FileCTRL is a light, opinionated, responsive, theme-able, and simple Text User Interface (TUI) file manager for Linux and macOS
"""
edition = "2021"
license = "MIT"
name = "filectrl"
readme = "README.md"
repository = "https://github.com/andornaut/filectrl"
version = "0.2.0"

[dependencies]
anyhow = "~1.0"
argh = "~0.1"
chrono = {version = "~0.4", default-features = false, features = ["clock"]}
cli-clipboard = "~0.4"
env_logger = {version = "~0.11", default-features = false}
etcetera = "~0.10"
log = {version = "~0.4", default-features = false, features = ["serde"]}
nix = {version = "~0", default-features = false, features = ["user"]}
notify = "~8"
open = "~5"
rat-text = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-text"}
rat-widget = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-widget"}
ratatui = {version = "~0.29", features = ["all-widgets", "serde"]}
serde = {version = "~1", features = ["derive"]}
smart-default = "~0.7"
textwrap = "~0.16"
toml = "~0.8"
unicode-segmentation = "~1"
unicode-width = "~0.2"
unix_mode = "~0.1"

[dev-dependencies]
cargo-husky = {version = "~1.5", default-features = false, features = ["precommit-hook", "run-cargo-test", "run-cargo-check"]}
test-case = "~3.3"

[profile.release]
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
lto = true # Enable Link Time Optimization
opt-level = 3 # Optimize for performance
panic = 'abort' # Abort on panic
strip = true # Symbols from Binary

[patch.crates-io]
rat-cursor = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-cursor"}
rat-event = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-event"}
rat-focus = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-focus"}
rat-ftable = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-ftable"}
rat-menu = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-menu"}
rat-popup = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-popup"}
rat-reloc = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-reloc"}
rat-scrolled = {git = "https://github.com/thscharler/rat-salsa", rev = "677fe2c", package = "rat-scrolled"}
