bg = "#423F2E"
fg = "#DDDCCC"
modifiers = []

[alert]
bg = ""
fg = "#9C9977"
modifiers = []

[alert.error]
bg = ""
fg = "#D30102"
modifiers = []

[alert.info]
bg = ""
fg = "#73c991"
modifiers = []

[alert.warn]
bg = ""
fg = "#d4731a"
modifiers = []

[breadcrumbs]
bg = ""
fg = "#DDDCCC"
modifiers = []

[breadcrumbs.ancestor]
bg = ""
fg = "#DDDCCC"
modifiers = []

[breadcrumbs.basename]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = []

[breadcrumbs.separator]
bg = ""
fg = "#9C9977"
modifiers = []

[file_modified_date.greater_than_year]
bg = ""
fg = "#FF0000" # Red
modifiers = []

[file_modified_date.less_than_day]
bg = ""
fg = "#00FF00" # Bright Green
modifiers = []

[file_modified_date.less_than_hour]
bg = ""
fg = "#00FFFF" # Cyan
modifiers = []

[file_modified_date.less_than_minute]
bg = ""
fg = "#87CEEB" # Sky Blue
modifiers = []

[file_modified_date.less_than_month]
bg = ""
fg = "#FFFF00" # Yellow
modifiers = []

[file_modified_date.less_than_year]
bg = ""
fg = "#FF00FF" # Magenta
modifiers = []

[file_size.bytes]
bg = ""
fg = "#87CEEB" # Sky Blue
modifiers = []

[file_size.gib]
bg = ""
fg = "#FFFF00" # Yellow
modifiers = []

[file_size.kib]
bg = ""
fg = "#00FFFF" # Cyan
modifiers = []

[file_size.mib]
bg = ""
fg = "#00FF00" # Bright Green
modifiers = []

[file_size.pib]
bg = ""
fg = "#FF0000" # Red
modifiers = []

[file_size.tib]
bg = ""
fg = "#FF00FF" # Magenta
modifiers = []

[file_type]
# Whether to apply colors defined in the $LS_COLORS environment variable (if set) on top of colors configured in this section
ls_colors_take_precedence = false

[file_type.block_device]
bg = "#FFFFD7" # 230
fg = "#808080" # 244
modifiers = ["bold"]

[file_type.character_device]
bg = "#FFFFD7" # 230
fg = "#808080" # 244
modifiers = ["bold"]

[file_type.directory]
bg = ""
fg = "#0087FF" # 33
modifiers = []

[file_type.directory_other_writable]
bg = "#262626" # 235
fg = "#0087FF" # 33
modifiers = []

[file_type.directory_sticky]
bg = "#0087FF" # 33
fg = "#FFFFD7" # 230
modifiers = []

[file_type.directory_sticky_other_writable]
bg = "#5F8700" # 64
fg = "#FFFFD7" # 230
modifiers = []

[file_type.door]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[file_type.executable]
bg = ""
fg = "#5F8700" # 64
modifiers = ["bold"]

[file_type.missing]
bg = ""
fg = ""
modifiers = []

[file_type.normal_file]
bg = ""
fg = "#E4E4E4" # 254
modifiers = []

[file_type.pipe]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[file_type.regular_file]
bg = ""
fg = "#E4E4E4" # 254
modifiers = []

[file_type.setgid]
bg = "#AF8700" # 136
fg = "#FFFFD7" # 230
modifiers = []

[file_type.setuid]
bg = "#D70000" # 160
fg = "#FFFFD7" # 230
modifiers = []

[file_type.socket]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[file_type.symlink]
bg = ""
fg = "#00AFAF" # 37
modifiers = ["bold"]

[file_type.symlink_broken]
bg = "#262626" # 235
fg = "#D70000" # 160
modifiers = []

[help]
bg = ""
fg = "#9C9977"
modifiers = []

[help.header]
bg = "#9C9977"
fg = "#1D1F21"
modifiers = []

[help.actions]
bg = ""
fg = "#DDDCCC"
modifiers = ["bold"]

[help.shortcuts]
bg = ""
fg = "#DDDCCC"
modifiers = []

[clipboard.copy]
bg = "#859900" # Olive Green
fg = "#1D1F21"
modifiers = []

[clipboard.cut]
bg = "#CB4B16" # Orange Red
fg = "#1D1F21"
modifiers = []

[notice.filter]
bg = "#70C0B1"
fg = "#1D1F21"
modifiers = []

[notice.progress]
bg = "#006B6B"
fg = "#70C0B1"
modifiers = []

[prompt.cursor]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = []

[prompt.input]
bg = "#373424"
fg = "#DDDCCC"
modifiers = []

[prompt.label]
bg = "#2AA198"
fg = "#1D1F21"
modifiers = []

[prompt.selected]
bg = "#59A799"
fg = "#DDDCCC"
modifiers = []

[scrollbar]
show_ends = false

[scrollbar.ends]
bg = "#777755"
fg = "#373424"
modifiers = []

[scrollbar.thumb]
bg = "#373424"
fg = "#9C9977"
modifiers = []

[scrollbar.track]
bg = ""
fg = "#777755"
modifiers = []

[status.directory]
bg = "#2AA198"
fg = "#1D1F21"
modifiers = []

[status.directory_label]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = []

[status.selected]
bg = "#2AA198"
fg = "#1D1F21"
modifiers = []

[status.selected_label]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = []

[table.body]
bg = "#423F2E"
fg = "#DDDCCC"
modifiers = []

[table.header]
bg = "#777755"
fg = "#1D1F21"
modifiers = []

[table.header_sorted]
bg = "#9C9977"
fg = "#1D1F21"
modifiers = []

[table.selected]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = []
