[theme]
bg = "#423F2E"
fg = "#DDDCCC"

[theme.alert]
fg = "#9C9977"

[theme.alert.error]
fg = "#D30102"

[theme.alert.info]
fg = "#859900"

[theme.alert.warn]
fg = "#b05533"

[theme.breadcrumbs]
bg = "#373424"

[theme.breadcrumbs.ancestor]
fg = "#DDDCCC"

[theme.breadcrumbs.basename]
bg = "#006B6B"
fg = "#DDDCCC"
modifiers = ["bold"]

[theme.breadcrumbs.separator]
fg = "#9C9977"

[theme.clipboard.copy]
bg = "#859900" # Olive Green
fg = "#24201A"

[theme.clipboard.cut]
bg = "#B58900" # Orange Red
fg = "#24201A"

[theme.clipboard.delete]
bg = "#b05533" # Rust
fg = "#24201A"

[theme.file_modified_date.less_than_minute]
fg = "#87CEEB" # Sky Blue

[theme.file_modified_date.less_than_hour]
fg = "#00FFFF" # Cyan

[theme.file_modified_date.less_than_day]
fg = "#00FF00" # Bright Green

[theme.file_modified_date.less_than_month]
fg = "#FFFF00" # Yellow

[theme.file_modified_date.less_than_year]
fg = "#FF00FF" # Magenta

[theme.file_modified_date.greater_than_year]
fg = "#FF0000" # Red

[theme.file_size.bytes]
fg = "#87CEEB" # Sky Blue

[theme.file_size.kib]
fg = "#00FFFF" # Cyan

[theme.file_size.mib]
fg = "#00FF00" # Bright Green

[theme.file_size.gib]
fg = "#FFFF00" # Yellow

[theme.file_size.tib]
fg = "#FF00FF" # Magenta

[theme.file_size.pib]
fg = "#FF0000" # Red

[theme.file_type]
# Whether to apply colors defined in the $LS_COLORS environment variable (if set) on top of colors configured in this section
ls_colors_take_precedence = false

[theme.file_type.block_device]
bg = "#FFFFD7" # 230
fg = "#808080" # 244
modifiers = ["bold"]

[theme.file_type.character_device]
bg = "#FFFFD7" # 230
fg = "#808080" # 244
modifiers = ["bold"]

[theme.file_type.directory]
fg = "#0087FF" # 33

[theme.file_type.directory_other_writable]
bg = "#262626" # 235
fg = "#0087FF" # 33

[theme.file_type.directory_sticky]
bg = "#0087FF" # 33
fg = "#FFFFD7" # 230

[theme.file_type.directory_sticky_other_writable]
bg = "#5F8700" # 64
fg = "#FFFFD7" # 230

[theme.file_type.door]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[theme.file_type.executable]
fg = "#5F8700" # 64
modifiers = ["bold"]

[theme.file_type.missing]

[theme.file_type.normal_file]
fg = "#E4E4E4" # 254

[theme.file_type.pipe]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[theme.file_type.regular_file]
fg = "#E4E4E4" # 254

[theme.file_type.setgid]
bg = "#AF8700" # 136
fg = "#FFFFD7" # 230

[theme.file_type.setuid]
bg = "#D70000" # 160
fg = "#FFFFD7" # 230

[theme.file_type.socket]
bg = "#FFFFD7" # 230
fg = "#AF8700" # 136
modifiers = ["bold"]

[theme.file_type.symlink]
fg = "#00AFAF" # 37
modifiers = ["bold"]

[theme.file_type.symlink_broken]
bg = "#262626" # 235
fg = "#D70000" # 160

[theme.help]
fg = "#9C9977"

[theme.help.header]
bg = "#9C9977"
fg = "#24201A"

[theme.help.actions]
fg = "#DDDCCC"
modifiers = ["bold"]

[theme.help.shortcuts]
fg = "#DDDCCC"

[theme.notice.filter]
bg = "#33A999"
fg = "#24201A"

[theme.notice.progress]
bg = "#006B6B"
fg = "#33A999"

[theme.prompt.cursor]
bg = "#006B6B"
fg = "#DDDCCC"

[theme.prompt.delete]
bg = "#b05533" # Rust
fg = "#24201A"

[theme.prompt.input]
bg = "#373424"
fg = "#DDDCCC"

[theme.prompt.label]
bg = "#33A999"
fg = "#24201A"

[theme.prompt.selected]
bg = "#2AA198"
fg = "#DDDCCC"

[theme.scrollbar]
show_ends = false

[theme.scrollbar.ends]
bg = "#7c7755"
fg = "#373424"

[theme.scrollbar.thumb]
bg = "#373424"
fg = "#9C9977"

[theme.scrollbar.track]
fg = "#7c7755"

[theme.status.detail]
bg = "#2AA198"
fg = "#24201A"

[theme.status.label]
bg = "#006B6B"
fg = "#DDDCCC"

[theme.table.body]
bg = "#423F2E"
fg = "#DDDCCC"

[theme.table.delete]
bg = "#B58900" # Amber
fg = "#24201A"

[theme.table.header]
bg = "#7c7755"
fg = "#24201A"

[theme.table.header_sorted]
bg = "#9C9977"
fg = "#24201A"
modifiers = ["bold"]

[theme.table.marked]
bg = "#2AA198"
fg = "#DDDCCC"

[theme.table.selected]
bg = "#006B6B"
fg = "#DDDCCC"
